---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
- type: document
  path: src/pages
  label: Ab
- type: document
  path: src/pages/about.tsx
  label: About
- type: document
  path: src/website-config.ts
  label: Home
  read_only: true
- type: directory
  path: src/content
  label: Posts
  create: all
  match: "**/*"
upload_dir: src/content/img
public_path: img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
